### PR TITLE
Add new iPhone 15 Series to DeviceKit

### PR DESCRIPTION
**Pull request by wo-ist-henry**
Add support for ne the iPhone Series, also added the new camera type Periscope to differentiate between the zoom capabilities that the iPhone 15 Pro Max and all the others has.

### CODE REVIEW

**Comment by LaurentiuUngur** [comment]
Maybe new watches should be added as well/

**Comment by wo-ist-henry** [comment]
@LaurentiuUngur I added them with a new PR, #361

**Review by ovidiuadorian-yonder — APPROVED** [review]

**Comment by Zandor300** [comment]
@wo-ist-henry Apple is using "telephoto camera" to describe the 5x lens on iPhone 15 Pro Max, so I think it is best to stick to that. I might be better to add extra functionality to DeviceKit to check how much zoom the device's telephoto camera is:

- iPhone 11 Pro: 2x
- iPhone 12 Pro (Max): 2x
- iPhone 13 Pro (Max): 3x
- iPhone 14 Pro (Max): 3x
- iPhone 15 Pro: 3x
- iPhone 15 Pro Max: 5x

But that is for another time, first need to add support for the devices. I cherrypicked your PR into a release PR, I will change it back to telephoto for now over there. https://github.com/devicekit/DeviceKit/pull/362

**Comment by Zandor300** [comment]
Cherrypicked this PR into https://github.com/devicekit/DeviceKit/pull/362

**Comment by Zandor300** [comment]
Merged to master through https://github.com/devicekit/DeviceKit/pull/362

**Pull request closed without merging**
