### PR TITLE
Support for iPhone 16 models and Apple Watch Series 10.

### PR DESCRIPTION
**Pull request by Zandor300**
Add support for iPhone 16 models and Apple Watch Series 10.

### CODE REVIEW

**Comment by t9mike** [comment]
I noticed iPhone16 placeholders still in mapToDevice:

      case "iPhoneTODO1": return iPhone16
      case "iPhoneTODO2": return iPhone16Plus
      case "iPhoneTODO3": return iPhone16Pro
      case "iPhoneTODO4": return iPhone16ProMax

**Comment by duke4e** [comment]
we can get the phone string via simulators:

case "iPhone17,3": return iPhone16
case "iPhone17,4": return iPhone16Plus
case "iPhone17,1": return iPhone16Pro
case "iPhone17,2": return iPhone16ProMax

**Comment by furiosFast** [comment]
> we can get the phone string via simulators:
> 
> case "iPhone17,3": return iPhone16 case "iPhone17,4": return iPhone16Plus case "iPhone17,1": return iPhone16Pro case "iPhone17,2": return iPhone16ProMax

for watch too

**Comment by arindamkb** [comment]
Please check this Wikipedia page, hardware strings of iPhone 16 series are updated here [https://en.wikipedia.org/wiki/List_of_iPhone_models](https://en.wikipedia.org/wiki/List_of_iPhone_models)

**Pull request merged**
