### PR TITLE
Add support for new 2019 September devices.

### LINKED ISSUE #199: Please support the new devices released at the 2019 September device.
Please support:

- iPhone 11
- iPhone 11 Pro
- iPhone 11 Pro Max
- The new iPad (10.2 inch - not sure what it's called) - [iPad 10.2](https://www.apple.com/ipad-10.2)

You can see here the new devices here: [Apple](https://www.apple.com)

Thanks!

### PR DESCRIPTION
**Pull request by Zandor300**
Adds support for the new devices announced at the September 2019 event:
- iPhone 11
  - `iPhone12,1`
- iPhone 11 Pro
  - `iPhone12,3`
- iPhone 11 Pro Max
  - `iPhone12,5`
- Apple Watch Series 5
  - `Watch5,1` and `Watch5,3` for 40mm
  - `Watch5,2` and `Watch5,4` for 44mm
- iPad (7th generation) *(aka iPad 10.2 inch)*
  - Unknown currently. Feel free to post it below if you have information.

---

Fixes #199

### CODE REVIEW

**Comment by aaronpearce** [comment]
Just thought I'd add that a 44mm Aluminium Sport is reporting as Watch5,2

**Comment by Zandor300** [comment]
Thanks @aaronpearce, I've added those.

**Comment by bizibizi** [comment]
waiting for release

**Comment by bizibizi** [comment]
Typos which break previous style:

Now:
 .iPhoneXS 
  .iPhoneXSMax
 .iPhoneXR

Was:  .iPhoneXs
  .iPhoneXsMax
 .iPhoneXr

**Comment by bizibizi** [comment]
also you did many changes in current naming? why?

**Comment by aaronpearce** [comment]
Those are styled that way in `master` currently. It is not a change done in this PR.

**Comment by bizibizi** [comment]
> Those are styled that way in `master` currently. It is not a change done in this PR.

oh, okay,
so, did you get read device identifiers or we are waiting?

**Comment by Zandor300** [comment]
The PR is ready for merging but @denisenepraunig needs to do that. We are waiting with the iPad (7th generation) because it isn’t released yet and we don’t know identifiers of it.

**Comment by denisenepraunig** [comment]
Thanks everybody! A pod update will be released tomorrow.

**Pull request merged**
