### PR TITLE
Add support for April 2021 devices

### PR DESCRIPTION
**Pull request by Zandor300**
Add support for the devices announced at the April 2021 Apple Event:

- iPad Pro (11-inch) (3rd generation)
- iPad Pro (12.9-inch) (5th generation)
- Apple TV 4K (2nd generation)

## TODO

- [x] Device Identifiers
- [ ] Support Pages
- [ ] Support Images

### CODE REVIEW

**Comment by gabors** [comment]
How is this coming along?

**Comment by Zandor300** [comment]
@gabors We're still waiting in device identifiers, support pages and support images. If Apple is slow again with the support pages and images, we could release early without this, but identifiers are important for detecting the current device.

**Comment by gabors** [comment]
> @gabors We're still waiting on device identifiers, support pages and support images. If Apple is slow again with the support pages and images, we could release early without this, but identifiers are important for detecting the current device.

Great thanks!
I was also noticing that the Apple TV 4K gen2 Simulator was not being detected as a simulator (AppleTV11,1) but that's likely also because you don't yet have that identifier in the framework.

**Comment by Zandor300** [comment]
@denisenepraunig I would say let's merge this and release 4.4.0. Then we can release a 4.4.1 when Apple eventually publishes the support pages.

**Comment by denisenepraunig** [comment]
Yeah totally agree here. I think our users would need the DeviceIdentifiers first and foremost, then support pages and alike.

**Review by denisenepraunig — DISMISSED** [review]
Looking good to me, thanks a lot @Zandor300!

Still waiting for Travis to finish before I merge it and release it.

**Pull request merged**
