### PR TITLE
Add canvas detection

### LINKED ISSUE #302: Check if the current device is running in SwiftUI previews
Basically just an implementation of https://stackoverflow.com/a/61741858/998335

### PR DESCRIPTION
**Pull request by JackYoustra**
Fixes #302

### CODE REVIEW

**Comment by JackYoustra** [comment]
@denisenepraunig why are the tests failing?

**Comment by Zandor300** [comment]
```
/Users/runner/work/DeviceKit/DeviceKit/Tests/Tests.swift:32:27: error: value of type 'Device' has no member 'isCanvas'
    XCTAssertFalse(device.isCanvas)
                   ~~~~~~ ^~~~~~~~
```

@JackYoustra `isCanvas` isn't available on tvOS. If you move your method in the Device class to be included on tvOS (and watchOS possibly), it should fix it.

**Review by denisenepraunig — APPROVED** [review]
Thanks @JackYoustra and @Zandor300!

**Review by denisenepraunig — APPROVED** [review]
Thank you @JackYoustra and @Zandor300

**Pull request merged**
