### PR TITLE
Add support for October 2020 devices

### PR DESCRIPTION
**Pull request by Zandor300**
- [x] Version increase
- [x] Update changelog

# iPhones
- iPhone 12
- iPhone 12 mini
- iPhone 12 Pro
- iPhone 12 Pro Max

**Tasks:**
- [x] Device Identifiers
- [ ] ~~Support Technical Specifications Links~~*
- [ ] ~~Support Images~~*

# iPad
- iPad Air (4th generation)

**Tasks:**
- [X] Device Identifier
- [ ] ~~Support Technical Specifications Link~~*
- [ ] ~~Support Image~~*

*Support Technical Specs and Image will be added later in favor of an earlier release.

### CODE REVIEW

**Comment by Tulleb** [comment]
Xcode 12.1 is out guys! Hope this MR will follow soon 😇
Thank you for the amazing work!

**Comment by denisenepraunig** [comment]
> Xcode 12.1 is out guys! Hope this MR will follow soon 😇
> Thank you for the amazing work!

Thanks @Tulleb 😊. You are right. We've been waiting for support images and links and therefore we didn't release yet. We decided to release the technical part (device identifiers) earlier and add the other things when they are available. Should be done today.

**Comment by AgileFlexAgency** [comment]
> > Xcode 12.1 is out guys! Hope this MR will follow soon 😇
> > Thank you for the amazing work!
> 
> Thanks @Tulleb 😊. You are right. We've been waiting for support images and links and therefore we didn't release yet. We decided to release the technical part (device identifiers) earlier and add the other things when they are available. Should be done today.

This is great news @denisenepraunig  👏

**Review by denisenepraunig — APPROVED** [review]
Thank you @Zandor300 😊👍

**Pull request merged**
