### PR TITLE
Fixed logo url in README.md

### PR DESCRIPTION
**Pull request by Zandor300**
Self explanatory: 
https://github.com/devicekit/DeviceKit/pull/172/files

### CODE REVIEW

**Comment by denisenepraunig** [comment]
You can merge it when you're ready. BR Denise & Dennis

**Comment by Zandor300** [comment]
@denisenepraunig I cannot commit to master. Its a protected branch and I do not have access to pretected branches in this repo.

**Comment by Zandor300** [comment]
@dennisweissmann @denisenepraunig Okay, I am unable to merge it because of the merge commit that is in this pull request: https://github.com/devicekit/DeviceKit/pull/172/commits/d0d12c45b1afc822b413f5162de95bf21a78173b

**Comment by Zandor300** [comment]
image

**Comment by dennisweissmann** [comment]
Sorry for the trouble, I just merged it for you, don’t know what’s wrong here (still only mobile) ... thanks again :)

**Pull request merged**
